config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  # resources will output basic CRUD routes
  # get '/posts', to: 'posts#index'
  # get '/posts/:id', to: 'posts#show'
  # get '/posts/new', to: 'posts#new'
  # post '/posts', to: 'posts#create'
  # post '/posts/:id/edit', to: 'posts#edit'
  # patch '/posts/:id/', to: 'posts#update'

  resources :posts, except: [:destroy] do
    resources :comments, only: [:create]
  end

  resources :categories, only: [:new, :create, :show]

  resources :users, only: [:create, :show]
  get 'register', to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :post_categories
  has_many :posts, through: :post_categories

  validates :name, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :post

  validates :body, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  # deviating from the convention
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories

  validates :title, presence: true, length: {minimum: 5}
  validates :url, presence: true
  validates :description, presence: true, uniqueness: true
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :category
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  # assumes foreign key named post_id
  has_many :posts
  has_many :comments

  # whenever registering a new user we want to make sure
  # the username is unique
  validates :username, presence: true, uniqueness: true

  # whenever password is sent in through controller
  # and save is triggered.. the validation will be hit
  # validates :password, presence: true, on: :create, length: {minimum: 5}

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    unless current_user
      flash[:error] = 'Must be logged in to do that.'
      redirect_to root_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_user, only: [:create, :new]

  def new # GET /categories/new
    @category = Category.new
  end

  def create # POST /categories
    @category = Category.new(category_params)

    if @category.save
      flash[:notice] = 'The Category has been created!'
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user

  def create
    # redirect_to a url
    # always render a template

    # setup instance variable first
    # or instance variables
    # check if save was successful
    # if it was flash message and redirect
    # else render a page
    @post = Post.find(params[:post_id])
    # we want to attach the comment to a post (post_id, user_id)
    @comment = @post.comments.new(comment_params)

    if @comment.save # This is where the errors will be saved
      flash[:notice] = 'Your comment was added!'
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end

  private

  # we don't need this method if we are not reusing this, but
  # its still nice to keep to convention
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update]
  before_action :require_user, only: [:new, :edit]
  # 1. setup instance variable for action
  # 2. redirect based on some condition

  def index # GET /posts
    @posts = Post.all
  end

  def new # GET /posts/new new_post_path
    @post = Post.new
  end

  def create # POST /posts posts_path
    @post = Post.new(post_params)
    @post.creator = current_user
    @post.category_ids = post_params[:category_ids]

    if @post.save
      flash[:notice] = 'Your post was created.'
      redirect_to posts_path
    else
      render :new
    end
  end

  def show # GET /posts/1 post_path
    @comment = Comment.new
  end

  def edit # GET /posts/1/edit edit_post_path
    @categories = Category.all
  end

  def update # PUT/PATCH /posts/1 post_path
    @post.category_ids = params[:category_ids]

    if @post.update(post_params)
      flash[:notice] = 'Your post has been updated'
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  private

  def post_params
    params.require(:post).
      permit(:title, :url, :description, category_ids: [])
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new # '/login' GET
  end

  def create # '/login' POST
    # find user
    # authenticate user
    # redirect to root_path with sucess message
    # else render :new with flash[:error]
    user = User.find_by(username: params[:username])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = 'You have been logged in successfully!'
      redirect_to root_path
    else
      flash[:error] = 'There was something wrong with your username or password'
      redirect_to login_path
    end
  end

  def destroy # '/logout' DELETE
    session[:user_id] = nil
    flash[:notice] = 'You have been successfully logged out.'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: [:show]

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)

    if user.save
      flash[:notice] = "You have registered successfully!"
      redirect_to login_path(user)
    else
      render :new
    end
  end

  def show
    @user = current_user
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def fix_url(str)
    str.starts_with?('http://') ? str : "http://#{str}"
  end

  def format_date(date)
    # 05/20/2014 2:44pm EDT
    # %l hour of the day blank padded
    date.strftime('%m/%d/%Y %l:%M%P %Z')
  end
end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %></span>

app/views/categories/new.html.erb
<%= render 'shared/content_title', title: 'Create New Category' %>

<% if @category.errors.any? %>
  <%= render 'shared/errors', errors: @category.errors %>
<% end %>

<div class="well">
  <%= form_for @category do |f| %>
    <div class="control-group">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <%= f.submit 'Create Category', class: 'btn btn-success' %>
  <% end %>
</div>

app/views/categories/show.html.erb
<% all_posts = link_to('All Posts', posts_path) %>
<%= render 'shared/content_title', title: "#{all_posts} &raquo; #{@category.name}".html_safe %>

<% @category.posts.each do |post| %>
  <%= render 'posts/post', post: post %>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>
</ul>
<div class="btn-group nav_item">
  <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
    Categories <span class="caret"></span>
  <% end %>
  <ul class="dropdown-menu">
    <% Category.all.each do |category| %>
      <li><%= link_to category.name, category_path(category) %></li>
    <% end %>
    <li class="divider"></li>
    <li>
      <%= link_to(new_category_path) do %>
        <i class="icon-plus"></i>
        New Category
      <% end %>
    </li>
  </ul>
</div>

<% if logged_in? %>
  <div class="nav_item">
    <%= link_to 'New Post', new_post_path, class: 'btn btn-success btn-small' %>
  </div>
<% end %>

<div class="nav_item">
  <% if logged_in? %>
    <div class="dropdown">
      <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
        <%= current_user.username %> <span class="caret"></span>
      <% end %>
      <ul class="dropdown-menu">
        <li><%= link_to 'profile', user_path(current_user) %></li>
        <li><%= link_to 'logout', logout_path, method: :delete %></li>
      </ul>
    </div>
  <% else %>
    <%= link_to 'Register', register_path, class: 'btn btn-small' %>
    <%= link_to 'Login', login_path, class: 'btn btn-small' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_form.html.erb
<%= render 'shared/content_title', title: 'Create a new post' %>

<% if @post.errors.any? %>
  <%= render 'shared/errors', errors: @post.errors %>
<% end %>

<div class="well">
  <%= form_for @post do |f| %>
    <div class="control-group">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class="control-group">
      <%= f.label :url %>
      <%= f.text_field :url %>
    </div>
    <div class="control-group">
      <%= f.label :description %>
      <%= f.text_area :description, rows: 5 %>
    </div>

    <%= f.collection_check_boxes(:category_ids,
                                 Category.all,
                                 :id,
                                 :name) %>

    <% btn_text = @post.new_record? ? 'Create Post' : 'Update Post' %>
    <%= f.submit btn_text, class: 'btn btn-success' %>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class="row">
  <div class="span8 well">
    <%= render post.categories %>

    <h4><%= link_to post.title, post %></h4>
    <p><%= fix_url(post.url) %></p>
    <% if logged_in? %>
      (<%= link_to 'edit', edit_post_path(post) %>)
    <% end %>
    <p><%= post.description %></p>
    <p>
      <span class="quiet">posted by:</span> <%= post.creator.username %>
      <small>at <%= format_date(post.created_at) %></small>
    </p>
    <small>
      <span>
        <%= link_to "#{post.comments.size} comments", post_path(post) %>
      </span>
    </small>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: 'All Posts' %>

<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<% if logged_in? %>
  <p class="pull-right">
    (<%= link_to 'edit this post', edit_post_path(@post) %>)
  </p>
<% end %>

<p>
  <%= render @post.categories %>
</p>

<%= render 'shared/content_title', title: @post.title %>

<p>
  <%= @post.description %>
</p>

<p>
  <%= link_to 'go back to all posts', posts_path %>
</p>
<hr>

<h5>Create a comment:</h5>
<%= form_for [@post, @comment] do |f| %> <!-- /posts/:post_id/comments -->
  <% if @comment.errors.any? %>
    <%= render 'shared/errors', errors: @comment.errors %>
  <% end %>

  <%= f.text_area :body %>
  <br>
  <%= f.submit 'Create Comment', class: 'btn btn-primary' %>
<% end %>

app/views/shared/_content_title.html.erb
<p class="lead">
  <%= title %>
  <hr>
</p>

app/views/shared/_errors.html.erb
<div class="alert alert-error">
  <h5>there were some errors:</h5>
  <ul>
    <% errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <%= render 'shared/errors', errors: @user.errors %>
<% end %>

<div class="well">
  <%= form_for @user do |f| %>
    <div class="input-group">
      <%= f.label :username %>
      <%= f.text_field :username %>
    </div>

    <div class="input-group">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>

    <div class="input-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>

    <div class="btn-group mt-2">
      <%= f.submit 'Register', class: 'btn btn-success' %>
    </div>
  <% end %>
</div>